sudo: required
dist: trusty

language: cpp

notifications:
  email:
      - jkmtravisnotify@gmail.com

compiler: gcc

branches:
  only:
    - develop

#addons:
  #apt:
    #sources:
    #- llvm-toolchain-precise-3.5

#addons:
  #apt:
    #packages:
    #- cmake
    #- llvm-3.4


before_install:
  # print the distro information
  - lsb_release -a
  # https://github.com/travis-ci/travis-ci/issues/1379
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  # install gcc 4.8
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # install swig
  - sudo apt-get -y install swig
  # install python headers
  - sudo apt-get -y install python-dev
  # install pip
  - sudo apt-get -y install python-pip
  # install numpy
  - sudo pip install numpy
  - mkdir ~/install

  # setup CMake 3.2.1
  - mkdir ~/install/cmake-3.2.1
  - cd ~/install/cmake-3.2.1
  - wget --no-check-certificate https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.Z
  - tar xf cmake-3.4.0-Linux-x86_64.tar.Z --strip-components=1

  ## get LLVM 3.5.1 sources
  #- mkdir -p ~/src/rr-deps/llvm-3.5.1
  #- cd ~/src/rr-deps/llvm-3.5.1
  #- wget http://llvm.org/releases/3.5.1/llvm-3.5.1.src.tar.xz
  #- tar xf llvm-3.5.1.src.tar.xz
  ## build LLVM 3.5.1
  #- mkdir -p ~/build/llvm-3.5.1
  #- cd ~/build/llvm-3.5.1
  #- ~/install/cmake-3.2.1/bin/cmake --version
  #- ~/install/cmake-3.2.1/bin/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install/llvm-3.5.1 ~/src/rr-deps/llvm-3.5.1/llvm-3.5.1.src
  #- make -j2 && make install

  # download LLVM 3.5.1 binaries
  - cd ~/install
  - wget http://sourceforge.net/projects/roadrunner-deps/files/ubuntu-12.04.5/llvm-3.5.1.tar.xz
  - tar xf llvm-3.5.1.tar.xz

  # roadrunner third party:
  - mkdir -p ~/build/roadrunner-tp
  - cd ~/build/roadrunner-tp
  - ~/install/cmake-3.2.1/bin/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install/roadrunner-tp $TRAVIS_BUILD_DIR/third_party
  - make -j2

install:
  - cd ~/build/roadrunner-tp
  - make install

before_script:
  - echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
  # roadrunner:
  - mkdir -p ~/build/roadrunner
  - cd ~/build/roadrunner
  - ~/install/cmake-3.2.1/bin/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install/roadrunner -DTHIRD_PARTY_INSTALL_FOLDER=~/install/roadrunner-tp -DLLVM_CONFIG_EXECUTABLE=~/install/llvm-3.5.1/bin/llvm-config -DBUILD_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so python2.7 -DBUILD_TESTS=ON -DBUILD_TEST_TOOLS=ON -DUSE_TR1_CXX_NS=ON -DBUILD_JAVA_INTERFACE=OFF "$TRAVIS_BUILD_DIR"

script:
  - cd ~/build/roadrunner
  - make -j2 && make install
  - ctest -VV
