sudo: false

language: cpp

compiler: gcc

branches:
  only:
    - develop
    - travis

#addons:
  #apt:
    #sources:
    #- llvm-toolchain-precise-3.5

#addons:
  #apt:
    #packages:
    #- cmake
    #- llvm-3.4

before_install:
  - mkdir ~/install
  # setup CMake 3.2.1
  - mkdir ~/install/cmake-3.2.1
  - cd ~/install/cmake-3.2.1
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.Z
  - tar xf cmake-3.2.1-Linux-x86_64.tar.Z --strip-components=1
  # get LLVM 3.5.1 sources
  - mkdir -p ~/src/rr-deps/llvm-3.5.1
  - cd ~/src/rr-deps/llvm-3.5.1
  - wget http://llvm.org/releases/3.5.1/llvm-3.5.1.src.tar.xz
  - tar xf llvm-3.5.1.src.tar.xz
  - mkdir -p ~/build/llvm-3.5.1
  - cd ~/build/llvm-3.5.1
  - ~/install/cmake-3.2.1/bin/cmake --version
  - ~/install/cmake-3.2.1/bin/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install/llvm-3.5.1 ~/src/rr-deps/llvm-3.5.1/llvm-3.5.1.src

install: true

before_script:
  - echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
  # third party:
  - mkdir -p ~/build/roadrunner-tp
  - cd ~/build/roadrunner-tp
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install/roadrunner-tp $TRAVIS_BUILD_DIR/third_party
  # roadrunner:
  - mkdir -p ~/build/roadrunner
  - cd ~/build/roadrunner
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install/roadrunner -DTHIRD_PARTY_INSTALL_FOLDER=~/install/roadrunner-tp -DBUILD_PYTHON=OFF -DBUILD_TESTS=OFF -DUSE_TR1_CXX_NS=ON -DBUILD_JAVA_INTERFACE=OFF -DBUILD_TEST_TOOLS=OFF "$TRAVIS_BUILD_DIR"

script:
  - cd ~/build/roadrunner-tp
  - make && make install